### ISSUE TITLE
From where do you got the `ros2_esp32_interfaces`?

### ISSUE THREAD

**Issue by Guelakais** [xRetry/ros2-esp32-rust#1]
I've looked on [crates](https://crates.io/) and there is no entry for the [`ros2_esp32_interfaces`](https://crates.io/search?q=ros2_esp32_interfaces). From where do you got them?

**Comment by solinvic** [comment]
Hello,
This used to be another repo of mine containing the message definitions.

This project is nothing serious. I was just testing some ROS2 crates for Rust. I ended up using [r2r](https://github.com/sequenceplanner/r2r) for my actual [project](https://github.com/xRetry/esp32-config-tool/tree/main), which I was quite happy with.
